[package]
name = "greg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.1"
actix-web-lab = { version = "0.20.2", features = ["spa"] }
anyhow = "1.0.79"
# clokwerk = "0.4.0"
# diesel = {version = "2.1.4", features = ["sqlite", "returning_clauses_for_sqlite_3_35"]}
dotenvy = "0.15.7"
libsql-client = "0.33.4"
reqwest = "0.11.24"
# libsqlite3-sys = {version = "0.28.0", features = ["bundled"]}
rss = "2.0.7"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
time = { version = "0.3.34", features = ["serde"] }
tokio = { version = "1.36.0", features = ["full"] }
tokio-cron-scheduler = "0.10.0"
url = "2.5.0"
uuid = { version = "1.7.0", features = ["v4"] }
