[package]
name = "greg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4" # p=.1
actix-web-lab = { version = "0.20", features = ["spa"] } # p=.2
anyhow = "1.0" # p=.79
dotenvy = "0.15" # p=.7
env_logger = "0.11" # p=.1
feed-rs = "1.4" # p=.0
libsql-client = "0.33" # p=.4
log = "0.4" # p=.20
reqwest = "0.11" # p=.24
serde = { version = "1.0", features = ["derive"] } # p=.196
serde_json = "1.0" # p=.113
time = { version = "0.3", features = ["serde"] } # p=.34
tokio = { version = "1.36", features = ["full"] } # p=.0
tokio-cron-scheduler = "0.10" # p=.0
url = "2.5" # p=.0
uuid = { version = "1.7", features = ["v4"] } # p=.0
