/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutSourcesRouteImport } from './routes/_layout.sources'
import { Route as LayoutRoadmapsRouteImport } from './routes/_layout.roadmaps'
import { Route as LayoutActivityRouteImport } from './routes/_layout.activity'
import { Route as AppRmapRouteRouteImport } from './routes/_app/rmap/route'
import { Route as LayoutRoadmapRoadmap_idRouteImport } from './routes/_layout.roadmap.$roadmap_id'
import { Route as AppRssChar123SourceIdChar125RouteImport } from './routes/_app/rss/{-$sourceId}'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSourcesRoute = LayoutSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRoadmapsRoute = LayoutRoadmapsRouteImport.update({
  id: '/roadmaps',
  path: '/roadmaps',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutActivityRoute = LayoutActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => LayoutRoute,
} as any)
const AppRmapRouteRoute = AppRmapRouteRouteImport.update({
  id: '/rmap',
  path: '/rmap',
  getParentRoute: () => AppRoute,
} as any)
const LayoutRoadmapRoadmap_idRoute = LayoutRoadmapRoadmap_idRouteImport.update({
  id: '/roadmap/$roadmap_id',
  path: '/roadmap/$roadmap_id',
  getParentRoute: () => LayoutRoute,
} as any)
const AppRssChar123SourceIdChar125Route =
  AppRssChar123SourceIdChar125RouteImport.update({
    id: '/rss/{-$sourceId}',
    path: '/rss/{-$sourceId}',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rmap': typeof AppRmapRouteRoute
  '/activity': typeof LayoutActivityRoute
  '/roadmaps': typeof LayoutRoadmapsRoute
  '/sources': typeof LayoutSourcesRoute
  '/rss/{-$sourceId}': typeof AppRssChar123SourceIdChar125Route
  '/roadmap/$roadmap_id': typeof LayoutRoadmapRoadmap_idRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rmap': typeof AppRmapRouteRoute
  '/activity': typeof LayoutActivityRoute
  '/roadmaps': typeof LayoutRoadmapsRoute
  '/sources': typeof LayoutSourcesRoute
  '/rss/{-$sourceId}': typeof AppRssChar123SourceIdChar125Route
  '/roadmap/$roadmap_id': typeof LayoutRoadmapRoadmap_idRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/_app/rmap': typeof AppRmapRouteRoute
  '/_layout/activity': typeof LayoutActivityRoute
  '/_layout/roadmaps': typeof LayoutRoadmapsRoute
  '/_layout/sources': typeof LayoutSourcesRoute
  '/_app/rss/{-$sourceId}': typeof AppRssChar123SourceIdChar125Route
  '/_layout/roadmap/$roadmap_id': typeof LayoutRoadmapRoadmap_idRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rmap'
    | '/activity'
    | '/roadmaps'
    | '/sources'
    | '/rss/{-$sourceId}'
    | '/roadmap/$roadmap_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rmap'
    | '/activity'
    | '/roadmaps'
    | '/sources'
    | '/rss/{-$sourceId}'
    | '/roadmap/$roadmap_id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_layout'
    | '/_app/rmap'
    | '/_layout/activity'
    | '/_layout/roadmaps'
    | '/_layout/sources'
    | '/_app/rss/{-$sourceId}'
    | '/_layout/roadmap/$roadmap_id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/sources': {
      id: '/_layout/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof LayoutSourcesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/roadmaps': {
      id: '/_layout/roadmaps'
      path: '/roadmaps'
      fullPath: '/roadmaps'
      preLoaderRoute: typeof LayoutRoadmapsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/activity': {
      id: '/_layout/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof LayoutActivityRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_app/rmap': {
      id: '/_app/rmap'
      path: '/rmap'
      fullPath: '/rmap'
      preLoaderRoute: typeof AppRmapRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_layout/roadmap/$roadmap_id': {
      id: '/_layout/roadmap/$roadmap_id'
      path: '/roadmap/$roadmap_id'
      fullPath: '/roadmap/$roadmap_id'
      preLoaderRoute: typeof LayoutRoadmapRoadmap_idRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_app/rss/{-$sourceId}': {
      id: '/_app/rss/{-$sourceId}'
      path: '/rss/{-$sourceId}'
      fullPath: '/rss/{-$sourceId}'
      preLoaderRoute: typeof AppRssChar123SourceIdChar125RouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppRmapRouteRoute: typeof AppRmapRouteRoute
  AppRssChar123SourceIdChar125Route: typeof AppRssChar123SourceIdChar125Route
}

const AppRouteChildren: AppRouteChildren = {
  AppRmapRouteRoute: AppRmapRouteRoute,
  AppRssChar123SourceIdChar125Route: AppRssChar123SourceIdChar125Route,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface LayoutRouteChildren {
  LayoutActivityRoute: typeof LayoutActivityRoute
  LayoutRoadmapsRoute: typeof LayoutRoadmapsRoute
  LayoutSourcesRoute: typeof LayoutSourcesRoute
  LayoutRoadmapRoadmap_idRoute: typeof LayoutRoadmapRoadmap_idRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutActivityRoute: LayoutActivityRoute,
  LayoutRoadmapsRoute: LayoutRoadmapsRoute,
  LayoutSourcesRoute: LayoutSourcesRoute,
  LayoutRoadmapRoadmap_idRoute: LayoutRoadmapRoadmap_idRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
